### ISSUE TITLE
"unsupported zone Turkey Standard Time"

### ISSUE THREAD

**Issue by Nainabbas** [nibdo/ical-js-parser#26]
Error while parsing outlook ics

**Comment by nibdo** [comment]
Hi, thanks for reporting this. This is because date library used in parser does not work well with longer named timezones like yours. 

I am looking for some solution how to transform it or handle it with different library, which I would rather avoid, but it is quite limiting for me too.

**Comment by nibdo** [comment]
I have added some workaround for next version (currently only beta 0.7.2-beta.7), but outlook is tricky.

From what I check, they sometimes send you timezone like "Central Europe Standard Time" which has to be corrected to "Central European Standard Time". This will need some manual catching those cases.

**Comment by nibdo** [comment]
Fixed in 0.7.2
