### ISSUE TITLE
Parsing failure for time values with "VALUE=DATE-TIME:"

### ISSUE THREAD

**Issue by AlexanderS** [nibdo/ical-js-parser#29]
According to the ical Format Definition (f.e. see [DTEND](https://www.kanzaki.com/docs/ical/dtend.html#def)) each time value can contain "VALUE=DATE-TIME".

Currently the parser fails with an error like: `Invalid date: VALUE=DATE-TIME:20221017T094212Z`.

Something like this would work:

```diff
diff --git a/src/toJSON/utils/dates.ts b/src/toJSON/utils/dates.ts
index ae90484..c283860 100644
--- a/src/toJSON/utils/dates.ts
+++ b/src/toJSON/utils/dates.ts
@@ -115,13 +115,20 @@ export const parseICalDate = (
   const isSimpleDate: boolean = !isTzidDate && !isAllDayEvent;

   if (isSimpleDate) {
-    const value = formatToIsoDate(iCalDate);
+    let baseDate: string = iCalDate;
+    if (iCalDate.indexOf('DATE-TIME:') !== -1) {
+      baseDate = iCalDate.slice(
+        iCalDate.indexOf('DATE-TIME:') + 'DATE-TIME:'.length
+      );
+    }
+
+    const value = formatToIsoDate(baseDate);

     if (!DateTime.fromISO(value).isValid) {
       throw Error(`Invalid date: ${value}`);
     }

-    return { value: formatToIsoDate(iCalDate) };
+    return { value: formatToIsoDate(baseDate) };
   }

   if (isAllDayEvent) {
```

I could create a pull request, but I do not know whether this would match the coding style.

**Comment by nibdo** [comment]
@AlexanderS thank you. I have added also parsing for "DATE:" without time.

Feel free to update it with PR, if you would like repository contribution, but it's up to you. :)
